# Generated by Django 4.2.3 on 2023-08-08 04:50

import MyMotoMadness.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motousermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[MyMotoMadness.accounts.validators.phone_validator]),
        ),
    ]
