# Generated by Django 4.2.3 on 2023-07-31 12:02

import MyMotoMadness.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motousermodel',
            name='first_name',
            field=models.CharField(max_length=30, validators=[MyMotoMadness.accounts.validators.check_name_symbols_for_non_alphabetical]),
        ),
        migrations.AlterField(
            model_name='motousermodel',
            name='last_name',
            field=models.CharField(max_length=30, validators=[MyMotoMadness.accounts.validators.check_name_symbols_for_non_alphabetical]),
        ),
    ]
