# Generated by Django 4.2.3 on 2023-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motousermodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
