# Generated by Django 4.2.3 on 2023-08-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_motousermodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motousermodel',
            old_name='slug',
            new_name='user_slug',
        ),
    ]
