# Generated by Django 4.2.3 on 2023-08-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_slug_motousermodel_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motousermodel',
            old_name='user_slug',
            new_name='slug',
        ),
    ]
