# Generated by Django 4.2.3 on 2023-08-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_slug_motousermodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motousermodel',
            old_name='slug',
            new_name='slug_user',
        ),
    ]
