# Generated by Django 4.2.3 on 2023-07-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotoEquipmentGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('gear_type', models.CharField(choices=[('Helmet', 'Helmet'), ('Race Suit One Part', 'Race Suit One Part'), ('Race Suit Two Parts', 'Race Suit Two Parts'), ('Bonet', 'Bonet'), ('Boots', 'Boots'), ('Gloves', 'Gloves'), ('Protectors', 'Protectors'), ('Other..', 'Other..')], max_length=20)),
                ('material_type', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('gear_image', models.ImageField(blank=True, null=True, upload_to='photos/gear_photos')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotoParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_part', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcyclesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('SuperSport', 'SuperSport'), ('SportBike', 'SportBike'), ('Chopper', 'Chopper'), ('Bober', 'Bober'), ('Cafe Racer', 'Cafe Racer'), ('Enduro', 'Enduro'), ('Cross', 'Cross'), ('Custom Bike', 'Custom Bike'), ('Cruiser', 'Cruiser'), ('Naked Bike', 'Naked Bike'), ('Street Fighter', 'Street Fighter'), ('Scooter', 'Scooter'), ('Retro Bike', 'Retro Bike'), ('Other..', 'Other..')], max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('engine_volume', models.PositiveIntegerField()),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photos/bike_photos')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleads.motorcyclesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MotoPartsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photos/part_photos')),
                ('moto_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleads.motoparts')),
            ],
        ),
        migrations.CreateModel(
            name='MotoEquipmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photos/equipment_photos')),
                ('moto_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleads.motorcyclesmodel')),
            ],
        ),
    ]
