# Generated by Django 4.2.3 on 2023-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotoGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('gear_type', models.CharField(max_length=15)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MotoParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_part', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('engine_volume', models.PositiveIntegerField()),
                ('manufacture_year', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=15)),
                ('price', models.FloatField()),
            ],
        ),
    ]
