# Generated by Django 4.2.3 on 2023-07-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoequipmentgear',
            name='gear_image',
        ),
    ]
