# Generated by Django 4.2.3 on 2023-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycles',
            name='odo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
