# Generated by Django 4.2.3 on 2023-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoequipmentgear',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motoparts',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycles',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
