# Generated by Django 4.2.3 on 2023-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcyclesmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
