# Generated by Django 4.2.3 on 2023-08-15 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0002_motorcycles_odo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycles',
            name='odo',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
