# Generated by Django 4.2.3 on 2023-07-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0002_remove_motoequipmentgear_gear_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoequipmentimages',
            name='moto_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleads.motoequipmentgear'),
        ),
    ]
