# Generated by Django 4.2.3 on 2023-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0004_rename_images_motoequipmentimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoparts',
            name='for_bike',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
