# Generated by Django 4.2.3 on 2023-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0004_rename_odo_motorcycles_odo_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycles',
            name='bike_type',
            field=models.CharField(choices=[('SuperSport', 'SuperSport'), ('SportBike', 'SportBike'), ('Chopper', 'Chopper'), ('Bober', 'Bober'), ('Cafe Racer', 'Cafe Racer'), ('Tourer', 'Tourer'), ('Sport Tourer', 'Sport Tourer'), ('Enduro', 'Enduro'), ('Cross', 'Cross'), ('Custom Bike', 'Custom Bike'), ('Cruiser', 'Cruiser'), ('Naked Bike', 'Naked Bike'), ('Street Fighter', 'Street Fighter'), ('Scooter', 'Scooter'), ('Retro Bike', 'Retro Bike'), ('Other..', 'Other..')], max_length=30),
        ),
    ]
