# Generated by Django 4.2.3 on 2023-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0005_motoparts_for_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcyclesmodel',
            name='horse_power',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
