# Generated by Django 4.2.3 on 2023-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleads', '0005_alter_motorcycles_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoequipmentgear',
            name='gear_type',
            field=models.CharField(choices=[('Helmet', 'Helmet'), ('Race Suit One Part', 'Race Suit One Part'), ('Jacket', 'Jacket'), ('Pants', 'Pants'), ('Race Suit Two Parts', 'Race Suit Two Parts'), ('Bonnet', 'Bonnet'), ('Boots', 'Boots'), ('Gloves', 'Gloves'), ('Protectors', 'Protectors'), ('Other..', 'Other..')], max_length=20),
        ),
    ]
