# Generated by Django 4.2.3 on 2023-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('article_type', models.CharField(choices=[('News', 'News'), ('Information', 'Information')], max_length=30)),
            ],
        ),
    ]
