# Generated by Django 4.2.3 on 2023-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='article_photos')),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=30)),
                ('article_type', models.CharField(choices=[('News', 'News'), ('Advices', 'Advices')], max_length=30)),
            ],
        ),
    ]
