# Generated by Django 4.2.3 on 2023-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article_type',
            field=models.CharField(choices=[('News', 'News'), ('Advices', 'Advices')], max_length=30),
        ),
    ]
