# Generated by Django 4.2.3 on 2023-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
