# Generated by Django 4.2.3 on 2023-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/article_photos'),
        ),
    ]
