# Generated by Django 4.2.3 on 2023-07-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlesmodel_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
