# Generated by Django 4.2.3 on 2023-09-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_articlesmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article_image',
            field=models.ImageField(upload_to='photos/article_photos'),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
