# Generated by Django 4.2.3 on 2023-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
