# Generated by Django 4.2.3 on 2023-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='message_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
