# Generated by Django 4.2.3 on 2023-08-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0002_mymessage_receiver_mymessage_sender_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymessage',
            old_name='receiver',
            new_name='receiver_delete',
        ),
    ]
