# Generated by Django 4.2.3 on 2023-08-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0003_rename_slug_mymessage_message_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymessage',
            old_name='message_slug',
            new_name='slug',
        ),
    ]
